version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - data-volume:/var/lib/rabbitmq
        - log-volume:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

volumes:
  data-volume:
  log-volume:

networks:
  rabbitmq_go_net:
    driver: bridge